# Generated by Django 4.2.4 on 2023-08-31 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taskly', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to='user',
        ),
    ]
